alppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4.urls')),
    path('subject/', include('story5.urls')),
    path('activity/', include('story6.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [

]

story4/urls.py
from django.urls import path
from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.home, name='home'),
    path('time/', views.time, name='time'),
    path('time/<str:index>/', views.time, name='time'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.subject, name='subject'),
    path('detail/<int:index>/', views.subject_detail, name='subject_detail'),
    path('add/', views.add_subject, name='add_subject'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('register/<int:index>/', views.register, name='register'),
]

main/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
	matkul = models.CharField('Subject', max_length=120, null=True)
	dosen = models.CharField('Lecturer', max_length=120, null=True)
	sks = models.IntegerField('Credit(s)', null=True)
	deskripsi = models.TextField('Description', blank=True)
	semester = models.CharField('Term', max_length=120, null=True, help_text='example : Odd 2019/2020')
	kelas = models.CharField('Classroom', max_length=120, null=True)

	def __str__(self):
		return self.matkul

class Task(models.Model):
	matkul = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True)
	tugas = models.CharField('Task', max_length=120, null=True)
	deadline = models.DateField('Deadline', max_length=120, null=True)

	class Meta:
		ordering = ['deadline']

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	kegiatan = models.CharField('Activity Name', max_length=120)
	
class Person(models.Model):
	kegiatan = models.ForeignKey('Activity', on_delete=models.CASCADE, null=True, blank=True)
	nama = models.CharField('Name', max_length=120)

story5/forms.py
from django.forms import ModelForm
from .models import Subject

class SubjectForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Subject
		fields = '__all__'

story6/forms.py
from django.forms import ModelForm
from .models import Activity, Person

class ActivityForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Activity
		fields = '__all__'

class PersonForm(ModelForm):
	class Meta:
		model = Person
		fields = ['nama']

main/views.py
from django.shortcuts import render

story4/views.py
from django.shortcuts import render
from django.utils.timezone import utc
import datetime

# Create your views here.
def home(request):
    return render(request, 'homepage.html')

def extra(request):
    return render(request, 'extra_page.html')

def time(request, index="0"):
	time_zone = (7 + int(index)) % 24
	utc_time = datetime.datetime.utcnow().replace(tzinfo=utc)
	timezone_time = datetime.datetime.utcnow() + datetime.timedelta(hours=time_zone)

	context= {
	    'timezone_time': timezone_time,
	    'utc_time': utc_time,
	    'utc': time_zone,
    }
	return render(request, 'time.html', context)

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Subject, Task
from .forms import SubjectForm
import datetime

# Create your views here.
def subject(request):
	if request.method == "POST":
		Subject.objects.get(id=request.POST['id']).delete()
		return redirect('/subject/')
	list_subject = Subject.objects.all()
	return render(request, 'subject_list.html', {'subject_list': list_subject})

def subject_detail(request, index):
	subject = Subject.objects.get(pk=index)
	task_list = Task.objects.filter(matkul_id=subject)

	overdue = task_list.filter(deadline__lt=datetime.date.today())
	near = task_list.filter(deadline__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(days=6)))
	far = task_list.filter(deadline__gte=datetime.date.today() + datetime.timedelta(days=7))

	context = {
		'subject' : subject,
		'overdue': overdue,
		'near' : near,
		'far' : far,
	}
	return render(request, 'subject_detail.html', context)

def add_subject(request):
	submitted = False
	if request.method == 'POST':
		form = SubjectForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/subject/add/?submitted=True')
	else:
		form = SubjectForm()
		if 'submitted' in request.GET:
			submitted = True
	return render(request, 'add_subject.html', {'form': form, 'submitted': submitted})

story6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

# Create your views here.
def activity(request):
	activity = Activity.objects.all()
	attendees = Person.objects.all()

	if request.method == "POST":
		Person.objects.get(id=request.POST['id']).delete()
		return redirect('/activity/')

	return render(request, 'activity.html', {'activity': activity, 'attendees': attendees})

def add_activity(request):
	if request.method == 'POST':
		form = ActivityForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/activity/')
	else:
		form = ActivityForm()
	return render(request, 'add_activity.html', {'form': form})

def register(request, index):
	if request.method == 'POST':
		form = PersonForm(request.POST)
		if form.is_valid():
			newPerson = Person(kegiatan=Activity.objects.get(id=index), nama=form.data['nama'])
			newPerson.save()
			return redirect('/activity/')
	else:
		form = PersonForm()
	return render(request, 'register.html', {'form': form})

story4/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Alifah Azka Nisrina {% endblock %}

{% block content %}
{% include 'navbar.html' %}
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/animate/animate.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="css/style.css" rel="stylesheet">

	<section id="hero">
		<div class="hero-container">
		<img class="profpic" src="{% static 'images/profile.jpg' %}" alt="Profile Picture">
		  <h1>Alifah Azka Nisrina <br></h1>
		  <h2>Let me tell u more about me</h2>
		</div>
	  </section><!-- #hero -->

  	<section id="about" class="container-fluid d-flex flex-wrap align-content-center ">
		<div class="section-header">
			<h3 class="section-title">ABOUT ME</h3>
		</div>
		  <section id="about">
			<div class="container">
			  <div class="row about-container">
				<div class="flex-container"> 
				</div>
				<div class="col-lg-6 background order-lg-2 order-1 wow fadeInRight"></div>
			  </div>
	  
			</div>
			<div class="row align-items-center justify-content-center">
				<div class="col-sm-5 mr-3">
					<div class="icon-box wow fadeInUp">
						<h4 class="title"><a href="">Full Name</a></h4>
						<p class="description">Alifah Azka Nisrina</p>
					  </div>
					<div class="icon-box wow fadeInUp">
						<div class="icon"><i class="fa fa-map-marker"></i></div>
						<h4 class="title"><a href="">Date Place of Birth</a></h4>
						<p class="description">Garut, 29 November 2001</p>
					  </div>
		  
					  <div class="icon-box wow fadeInUp" data-wow-delay="0.2s">
						<div class="icon"><i class="fa fa-graduation-cap"></i></div>
						<h4 class="title"><a href="">Education</a></h4>
						<p class="description">Undergraduate student at University of Indonesia <br>
						Student at Islamic Boarding School of College Student Al-Faqih Mandiri</p>
					  </div>
				</div>
				<div class="col-sm-4 mr-3">
					<img class="profpic" src="{% static 'images/profile.jpg' %}" alt="Profile Picture">
					<article class="text-justify">
						An organized and self-motivated human with the vision to collaborate the ideas with touch of detail and creativity. Possess the boldness to make decision and to deal with the challenges to reach her goals and objectives
					</article>
				</div>
				
	
			</div>
		  </section>

	</section>

	<section id="education" class="container-fluid">
		<section id="education">
			<div class="container wow fadeIn">
			  <div class="section-header">
				<h3 class="section-title">EDUCATION</h3>
				<p class="section-description">This is the place where i got my knowledge</p>
			  </div>
			  <div class="row">
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-child"></i></a></div>
					<h4 class="title"><a href="">2007</a></h4>
					<p class="description">TK At-Taufiq,  Garut.</p>
				  </div>
				</div>
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-pencil"></i></a></div>
					<h4 class="title"><a href="">2008-2010</a></h4>
					<p class="description">SDN Paminggir IV, Garut</p>
				  </div>
				</div>
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-pencil"></i></a></div>
					<h4 class="title"><a href="">2010-2013</a></h4>
					<p class="description">SDN Perumnas Cijerah 1, Bandung</p>
				  </div>
				</div>
	  
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-paper-plane"></i></a></div>
					<h4 class="title"><a href="">2013-2016</a></h4>
					<p class="description">SMPN 1 Bandung</p>
				  </div>
				</div>
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.4s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-book"></i></a></div>
					<h4 class="title"><a href="">2016-2019</a></h4>
					<p class="description">SMAN 8 Bandung</p>
				  </div>
				</div>
				<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.6s">
				  <div class="box">
					<div class="icon"><a href=""><i class="fa fa-graduation-cap"></i></a></div>
					<h4 class="title"><a href="">2019-now</a></h4>
					<p class="description">University of Indonesia <br>
					Information System, Computer Science
					</p>
				  </div>
				</div>
			  </div>

			</div>
		   
		  </section><!-- #education -->
	</section>

	<section id="activities">
		<div class="container wow fadeInUp">
		  <div class="section-header">
			<h3 class="section-title">Recent Activities</h3>
			<p class="section-description">my activities with my friends</p>
		  </div>
		  <div class="row">
			<div class="col-lg-3 col-md-6">
			  <div class="member">
				<div class="pic"><img src="{% static 'images/team-1.jpg' %}" alt=""></div>
				<h4>GTA Girls!</h4>
				<span>Balkon PPM Al-Faqih Mandiri</span>
				<div class="social">
				</div>
			  </div>
			</div>
  
			<div class="col-lg-3 col-md-6">
			  <div class="member">
				<div class="pic"><img src="{% static 'images/team-2.jpg' %}" alt=""></div>
				<h4>Cook and Work?</h4>
				<span>Sekre-Dapur PPM Al-Faqih Mandiri</span>
				<div class="social">
				</div>
			  </div>
			</div>
  
			<div class="col-lg-3 col-md-6">
			  <div class="member">
				<div class="pic"><img src="{% static 'images/team-3.jpg' %}" alt=""></div>
				<h4>Panitia PSB - OSA 2020</h4>
				<span>Halaman Mesjid Fatimah PPM Al-Faqih Mandiri</span>
				<div class="social">
				</div>
			  </div>
			</div>
  
			<div class="col-lg-3 col-md-6">
			  <div class="member">
				<div class="pic"><img src="{% static 'images/team-4.jpg' %}" alt=""></div>
				<h4>Play Play Play!</h4>
				<span>Mesjid Fatimah PPM Al-Faqih Mandiri</span>
				<div class="social">
				</div>
			  </div>
			</div>
		  </div>
  
		</div>
	  </section><!-- #Hobbies and Activities -->

	  <section id="contact">
		<div class="container wow fadeInUp">
		  <div class="section-header">
			<h3 class="section-title">Contact</h3>
			<p class="section-description">Contact me if you have any question or you want me to join your project!</p>
		  </div>
		</div>
  
		<div class="container wow fadeInUp mt-5">
		  <div class="row justify-content-center">
  
			<div class="col-lg-3 col-md-4">
  
			  <div class="info">
				<div>
				  <i class="fa fa-map-marker"></i>
				  <p>Gg Kebon Kangkung No. 11 B<br>Kiaracondong, Kota Bandung 40284</p>
				</div>
  
				<div>
				  <i class="fa fa-envelope"></i>
				  <p>alifah.azka@ui.ac.id</p>
				</div>
  
				<div>
				  <i class="fa fa-phone"></i>
				  <p>+62 85773522390</p>
				</div>
			  </div>
  
			  <div class="social-links">
				<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
				<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
				<a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
				<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
				<a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
			  </div>
  
			</div>    
		  </div>
  
		</div>
	  </section><!-- #contact -->
	  <!-- #about -->


{% endblock %}

story5/templates/add_subject.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Subject{% endblock %}
{% block content %}

{% include 'navbar.html' %}

<section class="container-fluid d-flex flex-wrap align-content-center ">
{% if submitted %}
	<div class="success p-5 col-12 text-center">
		Your subject was submitted successfully. Thank you :)
	</div>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story5:subject' %}" class="text-white">
			Back to Subject List
		</a>
	</button>
{% else %}
	<div class="section-title mx-auto text-center p-5"> 
		ADD SUBJECT
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>
{% endif %}

</section>

{% endblock content %}

story5/templates/subject_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ subject.matkul }} {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="#">Navbar</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
  
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav mr-auto">
		<li class="nav-item active">
		  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" href="#">Link</a>
		</li>
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Dropdown
		  </a>
		  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			<a class="dropdown-item" href="#">Action</a>
			<a class="dropdown-item" href="#">Another action</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" href="#">Something else here</a>
		  </div>
		</li>
		<li class="nav-item">
		  <a class="nav-link disabled" href="#">Disabled</a>
		</li>
	  </ul>
	  <form class="form-inline my-2 my-lg-0">
		<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
		<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	  </form>
	</div>
  </nav>
	<section class="container-fluid d-flex flex-wrap align-content-center ">
		<div class="section-title m-auto text-center"> 
			{{ subject.matkul }}
		</div>
  	  <table class="table table-bordered mx-5" style="width:90vw">
		<tbody>
			<tr>
				<td> <b> Lecturer </b> </td>
				<td> {{ subject.dosen }} </td>
			</tr>
			<tr>
				<td> <b> Credit(s) </b> </td>
				<td> {{ subject.sks }} </td>
			</tr>
			<tr>
				<td> <b> Term </b> </td>
				<td> {{ subject.semester }} </td>
			</tr>
			<tr>
				<td> <b> Classroom </b> </td>
				<td> {{ subject.kelas }} </td>
			</tr>
			<tr>
				<td> <b> Description </b> </td>
				<td> {{ subject.deskripsi }} </td>
			</tr>
		</tbody>
	  </table>

	  <table class="table table-bordered mx-5" style="width:90vw">
		  <tr> 
		  	<td> <b> Tasks </b> </td>
		  </tr>
		
		{% for x in overdue %}
		  <tr class="table-danger">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}

		{% for x in near %}
		  <tr class="table-warning">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}

		{% for x in far %}
		  <tr class="table-success">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}
	  </table>

	  <button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story5:subject' %}" class="text-white">
			Back to Subject List
		</a>
	  </button>
  	</section>

{% endblock %}

story5/templates/subject_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Subject List {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center"> 
			SUBJECT LIST
	</div>
	<table class="table table-bordered mx-5" style="width:90vw">
	  <thead class="thead-light text-center">
	    <tr>
	      <th>Subject</th>
	      <th>Lecturer</th>
	      <th>Credit(s)</th>
	      <th>Delete</th>
	    </tr>
	  </thead>
		<tbody>
		    {% for x in subject_list %}
			<tr>
				<td> <a href="detail/{{ x.id }}">{{ x.matkul }} </a> </td>
				<td> {{ x.dosen }} </td>
				<td class="text-center"> {{ x.sks }} </td>
				<td class="text-center"> 
					<form method="POST" action="{% url 'story5:subject' %}">
			          {% csrf_token %}
			          <input name="id" value="{{x.id}}" type="hidden">
			          <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2" style="font-size: 0.8rem;">Delete</button>
			        </form>
				</td>
			</tr>
		    {% endfor %}
		</tbody>
	</table>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story5:add_subject' %}" class="text-white">
			Add New Subject
		</a>
	</button>
</section>
{% endblock %}

story6/templates/activity.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Activity {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container-fluid d-flex flex-wrap align-content-center mt-5">
	<div class="section-title mx-auto text-center mt-5"> 
			ACTIVITY LIST
	  <a href="{% url 'story6:add_activity' %}" class="text-white">
		<button class="btn btn-primary d-flex mx-auto my-2 click">
			Add New Activity
		</button>
	  </a>
	</div>

	<div class="row w-100 justify-content-center">
		{% for x in activity %}
			<div class="col-4 m-4 p-4 rounded border">
				<ul class="list-group">
				  <li class="list-group-item list-group-item-secondary"> <b> {{ x.kegiatan }} </b> </li>

			      {% for y in attendees %}
				    {% if y.kegiatan == x %}
					  	<form method="POST" action="{% url 'story6:activity' %}">
					    {% csrf_token %}
					    <input name="id" value="{{y.id}}" type="hidden">
				  		<li class="list-group-item"> 
				  			<div class="d-flex justify-content-between"> 
				  				{{ y.nama }} 
					          <button type="submit" value="Submit" class="btn btn-primary" style="font-size: 0.8rem;"> 
					          x
					           </button>
					        </form>
				  			</div>
				  		</li>
				    {% endif %}
			      {% endfor %}
				</ul>

				<div class="section-title mx-auto text-center"> 
				  <a href="register/{{ x.id }}" class="text-white">
					<button class="btn btn-primary d-flex mx-auto my-2 click">
					  	Register Yourself
					</button>
				  </a>
				</div>
			</div>
		{% endfor %}
	</div>

</section>
{% endblock %}

story6/templates/add_activity.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Activity{% endblock %}
{% block content %}

{% include 'navbar.html' %}

<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		ADD NEW ACTIVITY
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>


{% endblock content %}

story6/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Regist Yourself{% endblock %}
{% block content %}

{% include 'navbar.html' %}

<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center p-5"> 
		REGIST YOURSELF
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>

</section>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="{% static 'css/new-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet"> 
        
        <title>{% block title %}{% endblock %}</title>

    </head>
    <body>
    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
    </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#navbar {
  overflow: hidden;
  background-color: #E06679;
  padding: 30px 20px;
  transition: 0.4s;
  position: fixed;
  width: 100%;
  top: 0;
  z-index: 99;
}

#navbar a {
  float: left;
  color: #ffffff;
  text-align: center;
  padding: 10px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 40px;
  font-family: "Open Sans", sans-serif;
}

#navbar #logo {
  font-size: 35px;
  font-weight: bold;
  transition: 0.4s;
}

#navbar a:hover {
  background-color: #F4D35E;
  color: #ffffff;
}

#navbar a.active {
  background-color: dodgerblue;
  color: #E06679;
}

#navbar-right {
  float: right;
}

@media screen and (max-width: 580px) {
  #navbar {
    padding: 20px 10px !important;
  }
  #navbar a {
    float: none;
    display: block;
    text-align: left;
  }
  #navbar-right {
    float: none;
  }
}
</style>
</head>
<body>

<!-- <div id="navbar">
  <a href="{% url 'story4:home' %}#hero" id="logo">🐾</a>
  <div id="navbar-right">
    <a class="" href="{% url 'story4:home' %}#hero">Home</a>
    <a href="{% url 'story4:home' %}#contact">Contact</a>
    <a href="{% url 'story4:home' %}#about">About</a>
    <a class="" href="{% url 'story5:subject' %}">My Subject</a>
    <a class="" href="{% url 'story6:activity' %}"> My Activities </a>
  </div>
</div> -->

<nav id = "navbar" class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="#">🐾</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'story4:home' %}#hero">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story4:home' %}#contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story5:subject' %}">My Subject</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story6:activity' %}">My Activities</a>
      </li>
    </ul>
  </div>
</nav>

<script>
// When the user scrolls down 80px from the top of the document, resize the navbar's padding and the logo's font size
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("navbar").style.padding = "10px 10px";
    document.getElementById("logo").style.fontSize = "30px";
  } else {
    document.getElementById("navbar").style.padding = "50px 10px";
    document.getElementById("logo").style.fontSize = "45px";
  }
}
</script>

</body>
</html>